### ISSUE TITLE
No wave written

### ISSUE THREAD

**Issue by qiuqiangkong** [faroit/stempeg#1]
Hi, 

    The write function does not write anything and no error message is shown. 

    I found when I remove "-acodec libfdk_aac" in write function it works. Looking forward for fixing the issue! 

Best wishes, 

Qiuqiang

**Comment by faroit** [comment]
Hi, 

thanks for looking into this. As I mentioned in tje readme, writing requires an ffmpeg version that can encode aac. I haven’t tried to use other encoders than lib_fdk because they are known to produce inferior quality. I will make another round of tests soon. 

Also I will output the error msgs in the next version

**Comment by faroit** [comment]
okay I now check for the available ffmpeg version and return an error.
This should be fixed.
